# Generated by Django 4.0.5 on 2022-09-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apply_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='offset',
        ),
    ]
