# Generated by Django 4.0.5 on 2022-09-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apply_status_alter_apply_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('1', 'PENDING'), ('2', 'ACCEPTED'), ('3', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
